name: iris_mlflow_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pip
  - pip:
      - mlflow==2.19.0
      - pandas==2.0.3
      - numpy==1.24.3
      - scikit-learn==1.3.0
